astraly-labs/pragma-node

migrations/2023-10-25-134954_add_currencies_table/down.sql, migrations/2023-10-25-134954_add_currencies_table/up.sql, src/domain/models/currency.rs, src/domain/models/entry.rs, src/domain/models/mod.rs, src/domain/models/publisher.rs, src/handlers/entries/convert_amount.rs, src/handlers/entries/create_entry.rs, src/handlers/entries/get_entry.rs, src/infra/db/schema.rs, src/infra/repositories/entry_repository.rs
- Dynamic Decimals
- Revert if pair_id unknown
- Add check if publisher is active
=> ✨ API improvements

src/infra/repositories/entry_repository.rs
The previous query was incorrect because
- It calculate the median from all prices available for a given source
The new query
- Select the latest price for a given pair id for each (publisher, source) combination
- It then calculates the median price and time for each source
I think using the median time makes more sense as we are using the median price. Also, I think we should add a check to remove prices which are very outdated (say older than 10 minutes). The reason we should do this is because if tomorrow `n/2+1` out of `n` publishers go down, our medians will be incorrect. If we can remove data from those `n/2+1` publishers by the time check, we can ensure we calculate the correct median from the correct data.
=> fix: median price calc

src/domain/models/entry.rs, src/handlers/entries/convert_amount.rs, src/handlers/entries/get_entry.rs, src/handlers/entries/get_volatility.rs, src/handlers/entries/mod.rs, src/handlers/entries/utils.rs, src/infra/errors.rs, src/infra/repositories/entry_repository.rs, src/main.rs, src/routes.rs
=> ✨ Realized volatility

pragma-entities/src/models/entry_error.rs, pragma-node/src/handlers/entries/get_onchain/mod.rs, pragma-node/src/handlers/entries/get_onchain/publishers.rs, pragma-node/src/handlers/entries/mod.rs
- Sets `aggregation_mode` query parameter to optional
- Cleanup some code
=> fix(onchain): default aggregation mode

Cargo.lock, pragma-node/Cargo.toml
Updated branch from akhercha to astraly-labs
=> dev: Fixed pragma monitoring branch

pragma-node/src/handlers/entries/mod.rs, pragma-node/src/infra/repositories/onchain_repository.rs
- onchain publishers component now also return daily updates per (pair_id, source)
=> feat(onchain/publishers): add daily updates count to components

compose.yaml, pragma-entities/migrations/2024-06-07-130038_add_publisher_signature/down.sql, pragma-entities/migrations/2024-06-07-130038_add_publisher_signature/up.sql, pragma-entities/src/models/entry.rs, pragma-entities/src/schema.rs, pragma-node/src/handlers/entries/create_entry.rs
- entities migration: column `publisher_signature` added - can be NULL for previous entries,
- new entries now push the publisher signature in the database
=> Added publisher_signature to offchain entries

Cargo.lock, pragma-node/Cargo.toml, pragma-node/src/handlers/entries/get_entry.rs, pragma-node/src/handlers/entries/get_ohlc.rs, pragma-node/src/handlers/entries/get_onchain/ohlc.rs, pragma-node/src/handlers/entries/mod.rs, pragma-node/src/infra/repositories/entry_repository.rs, pragma-node/src/main.rs, pragma-node/src/utils/doc_examples.rs, pragma-node/src/utils/mod.rs, pragma-node/src/utils/types.rs
- parse timestamp query param as an i64 and create associated util type for maintenance
- adds a new `doc_examples.rs` utils file for utopia doc helpers
- adds a new cors & logging layer
- handle different client messages more smoothly
- avoid panicking on client abrupt disconnection
=> feat: small ws improvements

pragma-node/src/handlers/entries/subscribe_to_entry.rs, pragma-node/src/handlers/entries/utils.rs, pragma-node/src/main.rs, pragma-node/src/utils/aws.rs
-  the pragma starkex signer is now optional, if not found the starkex endpoint will be disabled,
- fixed secret key retrieval
=> fix: Pragma signer fetching + being optional

pragma-node/src/servers/metrics.rs, pragma-node/src/types/ws/metrics.rs, pragma-node/src/types/ws/mod.rs
- The metrics are now correctly recorded
=> fixed: WS metrics

Cargo.lock, pragma-node/Cargo.toml, pragma-node/src/handlers/entries/constants.rs, pragma-node/src/handlers/entries/get_onchain/publishers.rs, pragma-node/src/infra/repositories/onchain_repository.rs, pragma-node/src/main.rs
- Cache for onchain publishers updates.
=> feat: Cache for publishers update

compose.yaml, pragma-node/src/handlers/entries/get_onchain/ohlc.rs, pragma-node/src/infra/repositories/onchain_repository.rs
- `candles_to_get` optional parameter used to specify the first candles retrieved
=> feat: OHLC endpoint, candles to retrieve parameter

compose.yaml, pragma-node/src/handlers/entries/get_onchain/ohlc.rs, pragma-node/src/main.rs, pragma-node/src/metrics.rs, pragma-node/src/servers/metrics.rs, pragma-node/src/types/ws/metrics.rs, pragma-node/src/types/ws/mod.rs
- Added a registry for our metrics & pass them into our state instead of using static constants
=> dev: Better prometheus metrics

pragma-node/src/handlers/entries/get_onchain/mod.rs, pragma-node/src/handlers/entries/mod.rs, pragma-node/src/infra/repositories/entry_repository.rs, pragma-node/src/infra/repositories/onchain_repository.rs
Resolve : #81 
- added routing param as in offchain endpoint (false by default)
This PR include a breaking change to the explorer because we changed data from decimal to hex as in offchain @EvolveArt
=> adding routing to onchain endpoint

pragma-common/src/types.rs, pragma-entities/src/error.rs, pragma-entities/src/models/checkpoint_error.rs, pragma-entities/src/models/entries/entry_error.rs, pragma-node/src/handlers/entries/get_onchain/mod.rs, pragma-node/src/handlers/entries/mod.rs, pragma-node/src/infra/repositories/onchain_repository.rs, pragma-node/src/types/mod.rs
Resolve : #84 
- The onchain Api now return a Vec of original result, even for normal usage
=> add timestamp range to onchain endpoint

scripts/run_dev.sh
Closes: #NA
- Fixed dev script
=> dev: Fixed backup from dev script

infra/pragma-node/postgres_migrations/15-create-indexes.sql
- Adds a migration to create necessary indexes
=> feat: indexes migration

pragma-node/src/infra/redis/mod.rs
Resolves: #NA
- `redis` now retrieves the latest block published using the key we published.
=> fix: Redis latest block retrieval

pragma-node/src/handlers/onchain/get_history.rs, pragma-node/src/infra/repositories/onchain_repository/history.rs, pragma-node/src/utils/mod.rs
- Fixed pair_id of the routed pair
=> fix: pair_id of routed pair

Cargo.lock, Cargo.toml, README.md, pragma-common/Cargo.toml, pragma-common/src/tracing.rs, pragma-entities/src/models/entries/entry.rs, pragma-ingestor/src/config.rs, pragma-ingestor/src/main.rs, pragma-node/Cargo.toml, pragma-node/src/config.rs, pragma-node/src/main.rs, pragma-node/src/servers/app/mod.rs
Resolves #110 
- Adds a new tracing layer to export logs to https://axiom.co/
- Load env vars at beginning in main
- Create tracing spans where necessary
=> feat: add axiom tracing

pragma-node/src/handlers/onchain/get_entry.rs
Resolves: #NA
- Possibility to ignore variations
=> feat: Onchain optional variations

infra/pragma-node/postgres_migrations/01-init.sql, pragma-node/src/handlers/optimistic_oracle/types.rs
- `dispute_id`definition in the table
- Adds missing `ToSchema` derives
=> feat(oo-requests): add `dispute_id`

Cargo.lock, Cargo.toml, pragma-node/src/handlers/optimistic_oracle/types.rs, pragma-node/src/infra/repositories/oo_repository/assertions.rs
- Add missing fields (setlle_caller, currency, dispute_id)
=> fix: oo api missing fields

Cargo.lock, infra/pragma-node/postgres_migrations/01-init.sql, openapi.json, pragma-node/Cargo.toml
Resolves: #NA
* Added new Pragma Devnet tables
* Fixed linters
=> feat: pragma chain tables

Cargo.lock, pragma-node/src/handlers/create_entry.rs, pragma-node/src/handlers/create_future_entry.rs, pragma-node/src/types/entries.rs, pragma-node/src/utils/conversion.rs, pragma-node/src/utils/mod.rs
- Fixes bugs in publishing future data
=> fix: future publish

pragma-node/src/constants/starkex_ws.rs, pragma-node/src/infra/repositories/entry_repository.rs
- Update maximum interval for ws endpoint
=> fix: starkex interval

pragma-common/src/utils.rs, pragma-node/src/constants/mod.rs, pragma-node/src/constants/others.rs, pragma-node/src/constants/starkex_ws.rs, pragma-node/src/handlers/get_entry.rs, pragma-node/src/infra/repositories/entry_repository.rs
- Fixes a bug in the routing where we want to route if the data is too old
=> fix: routing 

README.md, pragma-ingestor/src/main.rs, pragma-node/src/handlers/create_entry.rs, pragma-node/src/handlers/create_future_entry.rs, pragma-node/src/handlers/get_entry.rs, pragma-node/src/handlers/get_expiries.rs, pragma-node/src/handlers/get_ohlc.rs, pragma-node/src/handlers/get_volatility.rs, pragma-node/src/handlers/merkle_feeds/get_merkle_proof.rs, pragma-node/src/handlers/merkle_feeds/get_option.rs, pragma-node/src/handlers/onchain/get_checkpoints.rs, pragma-node/src/handlers/onchain/get_entry.rs, pragma-node/src/handlers/onchain/get_history.rs, pragma-node/src/handlers/onchain/get_publishers.rs, pragma-node/src/handlers/onchain/subscribe_to_ohlc.rs, pragma-node/src/handlers/subscribe_to_entry.rs, pragma-node/src/handlers/subscribe_to_price.rs, pragma-node/src/main.rs, pragma-node/src/server/middlewares.rs, pragma-node/src/server/mod.rs, pragma-node/src/types/pricer.rs
Resolves: #NA
* Added more logs & tracing for signoz.
=> feat: Better logs integration with Signoz

Cargo.lock, Cargo.toml, compose.dev.yaml, pragma-entities/src/models/entries/entry_error.rs, pragma-node/Cargo.toml, pragma-node/src/caches.rs, pragma-node/src/constants/caches.rs, pragma-node/src/handlers/create_entry.rs, pragma-node/src/handlers/create_future_entry.rs, pragma-node/src/handlers/mod.rs, pragma-node/src/handlers/publish_entry_ws.rs, pragma-node/src/handlers/subscribe_to_entry.rs, pragma-node/src/infra/repositories/entry_repository.rs, pragma-node/src/main.rs, pragma-node/src/metrics.rs, pragma-node/src/server/routes.rs, pragma-node/src/types/auth.rs, pragma-node/src/types/entries.rs, pragma-node/src/types/mod.rs, pragma-node/src/types/ws.rs, pragma-node/src/utils/conversion.rs, pragma-node/src/utils/kafka.rs, pragma-node/src/utils/macros.rs, pragma-node/src/utils/mod.rs, pragma-node/src/utils/signing/mod.rs, pragma-node/src/utils/signing/starkex.rs
Closes #153 
- Introduces a new websocket endpoint to publish data
- Authentication is done by sending a `login` message at first
Associated with https://github.com/astraly-labs/pragma-sdk/pull/245
=> feat: publish websocket endpoint

pragma-node/src/utils/mod.rs
- Add support for timestamp both in millis and seconds
=> feat: convert_timestamp_to_datetime macro

pragma-common/src/types/entries.rs, pragma-node/src/handlers/publish_entry_ws.rs
- Adds a better `Display` trait impl for spot/future/perp entries
- Reset session correctly on new loggin request
=> fix: minor changes

.github/workflows/pragma.yaml, Cargo.lock, Cargo.toml, pragma-entities/src/models/entries/entry_error.rs, pragma-node/Cargo.toml, pragma-node/src/handlers/get_entry.rs, pragma-node/src/handlers/get_ohlc.rs, pragma-node/src/handlers/mod.rs, pragma-node/src/handlers/stream/stream_multi.rs, pragma-node/src/handlers/subscribe_to_entry.rs, pragma-node/src/server/routes.rs
- Add back swagger ui on `/node/v1/docs`
- Improve OpenAPI schema examples
=> feat: improve a bit endpoints documentation

pragma-common/src/types/mod.rs, pragma-node/src/handlers/get_entry.rs, pragma-node/src/handlers/stream/common.rs, pragma-node/src/handlers/stream/stream_multi.rs, pragma-node/src/handlers/stream/stream_single.rs, pragma-node/src/infra/repositories/entry_repository.rs, pragma-node/src/infra/repositories/onchain_repository/entry.rs, pragma-node/src/utils/sql.rs, tests/e2e/common/utils/pragma_node.rs
- Removed `Mean` from `AggregationMode` enum
- Updated interval specifier to include new `FiveMinutes` interval and ensure proper handling of Twap aggregation.
- Fix broken routing without currencies table 
- Fix queries for `perp` data type
=> fix: correct some bugs and cleanup

pragma-node/src/handlers/mod.rs
=> fix: stream multi param deserialization

pragma-ingestor/src/config.rs, pragma-ingestor/src/db/process.rs, pragma-ingestor/src/main.rs, pragma-node/Cargo.toml
- Unified the batching logic to improve consistency and maintainability.
- Customized the Kafka environment settings for better configuration and flexibility.
=> refactor: unify batching logic and customize Kafka environment

pragma-node/src/handlers/get_ohlc.rs, pragma-node/src/handlers/websocket/mod.rs, pragma-node/src/handlers/websocket/subscribe_to_ohlc.rs, pragma-node/src/infra/repositories/entry_repository.rs, pragma-node/src/server/routes.rs, pragma-node/src/utils/mod.rs
=> feat: ohlc support for offchain db

pragma-entities/migrations/2025-05-15-183921_create-oi-table/down.sql, pragma-entities/migrations/2025-05-15-183921_create-oi-table/up.sql, pragma-entities/src/lib.rs, pragma-entities/src/models/mod.rs, pragma-entities/src/models/open_interest.rs, pragma-entities/src/schema.rs, pragma-ingestor/src/db/insert.rs, pragma-ingestor/src/db/process.rs, pragma-ingestor/src/main.rs, pragma-node/src/handlers/mod.rs, pragma-node/src/handlers/open_interest/get_historical_open_interest.rs, pragma-node/src/handlers/open_interest/get_instruments.rs, pragma-node/src/handlers/open_interest/get_open_interest.rs, pragma-node/src/handlers/open_interest/mod.rs, pragma-node/src/infra/repositories/mod.rs, pragma-node/src/infra/repositories/open_interest_repository.rs
=> feat: add support for io

.gitignore, Cargo.lock, Cargo.toml, pragma-historical/Cargo.toml, pragma-historical/README.md, pragma-historical/src/main.rs, pragma-historical/src/sources/hyperliquid.rs, pragma-historical/src/sources/mod.rs, pragma-historical/src/sources/paradex.rs, pragma-node/src/infra/repositories/funding_rates_repository.rs
Resolves: #NA
* We added a new CLI tool that allows us to populate our database with historical entries
* Only works for funding rates for now
=> feat: Historical CLI

cloudbuild.yaml
- This will help to rollback .
=> feat: add short SHA tags for ingestor and node Docker images
