pragma-entities/migrations/2024-01-19-113453_add_twap_aggregates/down.sql, pragma-entities/migrations/2024-01-19-113453_add_twap_aggregates/up.sql, pragma-node/src/handlers/entries/get_entry.rs, pragma-node/src/handlers/entries/mod.rs, pragma-node/src/infra/repositories/entry_repository.rs
- Adds a new `aggregation` query parameter
- Adds TWAP materialized views
=> ✨ Add TWAP aggregation

Cargo.lock, infra/pragma-node/postgres_migrations/01-init.sql, pragma-entities/src/dto/entry.rs, pragma-entities/src/models/entry.rs, pragma-node/Cargo.toml, pragma-node/src/handlers/entries/create_entry.rs, pragma-node/src/handlers/entries/get_entry.rs, pragma-node/src/handlers/entries/utils.rs, pragma-node/src/infra/repositories/entry_repository.rs, pragma-node/src/infra/repositories/onchain_repository.rs
Resolves: #44 
- `NaiveDateTime` to `DateTime<Utc>`,
- `TIMESTAMP` database fields to `TIMESTAMPTZ`
⚠ Currently the pragma-monitoring branch is `akhercha/pragma-monitoring` - needs to be update to astraly-labs when branch is merged there.
=> dev: Updated NaiveDateTime to DateTime<Utc>

infra/pragma-node/postgres_migrations/03-create-entries-index.sql, pragma-node/src/infra/repositories/onchain_repository.rs
- Updates the inactive publisher condition to `daily_updates == 0`
- Fixes the publisher components' query
- Adds a new index to the postgres migration
=> fix(onchain): publishers components

Cargo.lock, infra/pragma-node/postgres_migrations/01-init.sql, pragma-common/src/types.rs, pragma-entities/src/dto/entry.rs, pragma-entities/src/models/entry.rs, pragma-node/Cargo.toml, pragma-node/src/handlers/entries/create_entry.rs, pragma-node/src/handlers/entries/get_entry.rs, pragma-node/src/handlers/entries/utils.rs, pragma-node/src/infra/repositories/entry_repository.rs, pragma-node/src/infra/repositories/onchain_repository.rs
We have alerts in our testnet about entries not being published for a long time even though they are.
Probably related to this timezone change.
We decided to revert it.
=> Revert changes UTC

pragma-common/src/types.rs, pragma-node/src/handlers/entries/get_onchain/ohlc.rs, pragma-node/src/handlers/entries/utils.rs, pragma-node/src/infra/repositories/onchain_repository.rs, pragma-node/src/main.rs, pragma-node/src/routes.rs
- Removed all path and query params from the ohlc ws route
- All params are now passed through subscription message
- Only one pair can be subscribed on this endpoint
---
Motivation for this change is AWS API Gateway.
=> feat: refactor onchain OHLC ws endpoint

pragma-entities/src/dto/entry.rs, pragma-node/src/handlers/entries/get_entry.rs, pragma-node/src/handlers/entries/get_ohlc.rs, pragma-node/src/handlers/entries/mod.rs
Resolves #57 
Timestamps are now in seconds to align with SDK spec
=> fix: invalid timestamp

infra/pragma-node/Dockerfile
Fixes an error on deployment
```bash
thread 'main' panicked at /home/pragma-node/registry/src/index.crates.io-6f17d22bba15001f/hyper-rustls-0.24.2/src/config.rs:48:9: no CA certificates found
```
- Install `ca-certifcates` in pragma-node dockerfile
=> fix: install ca-certificates

Cargo.lock, pragma-entities/src/error.rs, pragma-entities/src/models/checkpoint_error.rs, pragma-entities/src/models/entries/entry_error.rs, pragma-node/Cargo.toml, pragma-node/src/handlers/entries/get_onchain/ohlc.rs, pragma-node/src/handlers/entries/get_volatility.rs, pragma-node/src/types/ws/metrics.rs, pragma-node/src/types/ws/mod.rs
Resolves #70 
- Adds rate limiting in terms of bytes that can be sent to the client
We could have added a limit in terms of connections that can be made with the server, but it's not useful as we already limit the bytes there will be a theoretical limit in the number of connections that can be made anyways.
=> feat: ip rate limiting on ws endpoints

compose.yaml, pragma-entities/migrations/2024-07-02-232003_add_median_aggregates/down.sql, pragma-entities/migrations/2024-07-02-232003_add_median_aggregates/up.sql, pragma-entities/migrations/2024-07-02-232723_new_ohlc_aggs/down.sql, pragma-entities/migrations/2024-07-02-232723_new_ohlc_aggs/up.sql, pragma-node/src/infra/repositories/entry_repository.rs
- Our method to compute the OHLC value from the offchain database was wrong. We now compute it from the median price of the entries published every 10s, see `price_10_s_agg`
=> fix: OHLC computation method

pragma-common/src/types.rs, pragma-node/src/handlers/entries/get_onchain/mod.rs, pragma-node/src/handlers/entries/mod.rs, pragma-node/src/infra/repositories/onchain_repository.rs
- Adds a new `variations` field to the `/onchain/x/y` endpoint which returns the 1hour/1day/1week variations.
=> feat: add variations to onchain data

pragma-entities/src/models/entries/entry_error.rs, pragma-node/src/handlers/entries/create_entry.rs, pragma-node/src/handlers/entries/create_future_entry.rs, pragma-node/src/handlers/entries/mod.rs, pragma-node/src/main.rs, pragma-node/src/types/entries.rs, pragma-node/src/utils/mod.rs, pragma-node/src/utils/signing/mock/typed_data_example.json, pragma-node/src/utils/signing/mock/typed_data_felt_array_example.json, pragma-node/src/utils/signing/mock/typed_data_long_string_example.json, pragma-node/src/utils/signing/mock/typed_data_struct_array_example.json, pragma-node/src/utils/signing/mod.rs, pragma-node/src/utils/signing/typed_data.rs
Linked to:
https://github.com/astraly-labs/pragma-sdk/issues/155
Following the `starknet.py` version bump, the way to use `TypedData` has slightly change and requires now two new fields (mandatory). They've been added so the offchain publishing works correctly (tested locally & it works ✅).
Currently, the function has a `is_legacy` argument for messages still signed the old way. We want to support that for 1-2 months than delete it.
=> fix: Updated typed_data following starknet.py bump

pragma-node/src/handlers/entries/get_onchain/mod.rs, pragma-node/src/handlers/entries/mod.rs
- Adds a new `components` query param which defaults to `true` to specify if we want all the sources that for each entry.
- If we are querying for a timestamp range, don't get the variations
=> feat(onchain): components query param

pragma-entities/src/models/entries/entry.rs, pragma-node/src/handlers/entries/get_entry.rs, pragma-node/src/infra/repositories/entry_repository.rs
Resolves: #NA
- Our offchain entry aggregation returns now the latest timestamp that a source had an entry published.
=> fix: Offchain entry timestamp

pragma-common/src/types/mod.rs, pragma-node/examples/starkex.rs, pragma-node/src/handlers/subscribe_to_entry.rs, pragma-node/src/infra/repositories/entry_repository.rs
Following Extended integration, we are applying a few changes
- Add back the `:MARK` suffix in the response for mark prices
- Scale prices to 18 decimals before signing following [docs](https://docs.starkware.co/starkex/perpetual/shared/asset_quantities_in_starkex.html#calculating_starkex_internal_prices) requirements
=> fix: starkex integration fixes

pragma-common/README.md
"Merkle Tree implementation" (./types/merkle_tree.rs) link is invalid. Corrected to (./src/types/merkle_tree.rs).
=> docs: fix invalid link README.md

pragma-common/src/types/mod.rs, pragma-common/src/types/pair.rs, pragma-node/src/handlers/get_entry.rs, pragma-node/src/handlers/get_expiries.rs, pragma-node/src/handlers/get_ohlc.rs, pragma-node/src/handlers/get_volatility.rs, pragma-node/src/handlers/onchain/get_checkpoints.rs, pragma-node/src/handlers/onchain/get_entry.rs, pragma-node/src/handlers/onchain/get_history.rs, pragma-node/src/handlers/publish_entry_ws.rs, pragma-node/src/infra/repositories/entry_repository.rs, pragma-node/src/infra/repositories/onchain_repository/entry.rs, pragma-node/src/infra/repositories/onchain_repository/history.rs, pragma-node/src/utils/conversion.rs, pragma-node/src/utils/mod.rs
Closes #119 
This PR introduces a new `Pair` type in the `pragma-common` module to replace string-based pair handling.
- Adding a new `pair.rs` module in `pragma-common/src/types/`
- Refactoring pair-related utility functions to use the new `Pair` struct
- Updating repositories and handlers to use the new `Pair` type
- Simplifying pair conversion and manipulation logic
- Removing deprecated conversion utility functions
The new `Pair` type provides a more type-safe and structured approach to handling currency pairs throughout the project.
=> feat: introduce Pair type for improved pair handling

pragma-entities/src/lib.rs, pragma-entities/src/macros.rs, pragma-entities/src/models/entries/entry.rs, pragma-node/src/handlers/get_entry.rs, pragma-node/src/infra/repositories/entry_repository.rs, pragma-node/src/utils/mod.rs
Resolves: #175 
The last updated timestamp is now correctly restricted when a `timestamp` parameter is provided.
=> fix: Last updated timestamp

pragma-common/src/types/entries.rs, pragma-node/src/handlers/publish_entry_ws.rs, pragma-node/src/utils/mod.rs
Introduces a new MarketEntry enum in entries.rs to handle both spot and perpetual market entries. Updates related utility functions and handlers to support the new enum, enabling more flexible market data representation.
=> feat: Add MarketEntry enum to support multiple market types

pragma-entities/src/error.rs, pragma-entities/src/models/entries/entry_error.rs, pragma-node/src/handlers/publish_entry_ws.rs, pragma-node/src/utils/ws.rs
- On every update interval tick we check if the connection is inactive and if so we close it. To keep the connection alive the client should send any text/binary message or `Ping`
- We set a default timeout of 1min for now
=> feat: Add WebSocket inactivity timeout

Cargo.lock, Cargo.toml, pragma-entities/migrations/2025-04-20-145559_create-funding-rates-table/down.sql, pragma-entities/migrations/2025-04-20-145559_create-funding-rates-table/up.sql, pragma-entities/src/dto/future_entry.rs, pragma-entities/src/lib.rs, pragma-entities/src/models/entries/future_entry.rs, pragma-entities/src/models/funding_rate.rs, pragma-entities/src/models/mod.rs, pragma-entities/src/schema.rs, pragma-ingestor/Cargo.toml, pragma-ingestor/src/config.rs, pragma-ingestor/src/db.rs, pragma-ingestor/src/error.rs, pragma-ingestor/src/main.rs
- Creates a new table `funding_rates`
- Update `pragma-ingestor` to fill this table with entries from kafka
We spawn `NUM_CONSUMERS` consumers for each topic.
Each consumer sends data through a bounded `mpsc` channel.
Other tasks process these data points with a buffer system i.e we insert in db by batch.
=> feat: funding rates table ingested from kafka

Cargo.lock, pragma-historical/Cargo.toml, pragma-historical/src/main.rs, pragma-ingestor/Cargo.toml, pragma-ingestor/src/main.rs, pragma-node/Cargo.toml, pragma-node/src/main.rs
- Added rustls version 0.23.31 to Cargo.toml files across multiple projects.
- Implemented default crypto provider initialization for rustls in main.rs files of ingestor, historical, and node modules.
=> feat: add rustls dependency with crypto provider initialization
